### ISSUE TITLE
Using LightState data returned from listLights

### ISSUE THREAD

**Issue by torresmi** [damienklinnert/elm-hue#13]
A common case I ran into is wanting to get all lights, and show them with their current state. 

`LightDetails` is returned from `listLights`, but ignores the `LightState` data also returned from the JSON response. https://github.com/damienklinnert/elmhue/blob/master/tests/src/Resource/Lights.elm#L12
This requires separate `getLightState` calls for every light to get the same data returned from the previous response.

It might be worth eventually making the change to return the `LightState` data when calling `listLights`. Maybe by adding it as a property to `LightDetails`?

``` elm
type alias LightDetails =
    { 
    ...
    , state : LightState
    ...
    }
```

**Comment by damienklinnert** [comment]
Love the suggestion, do you want to tackle it?

**Comment by torresmi** [comment]
I'd love to, but I'm having second thoughts about adding `LightState` to `LightDetails`.

If you store `LightDetails` in your model, then you would also have to keep that nested state record updated. Then it feels sort of opinionated by having your light state be maintained  in `LightDetails`. 

Does that sound like a valid concern? Maybe storing `LightDetails` isn't even a good idea. Since this is just an enhancement, it might be best to experiment with it before changing `LightDetails`?

**Comment by damienklinnert** [comment]
Valid concern. How about introducing a new function called getLightDetailsAndStates that returns a Tulpe of LightDetails and a list of LightStates?

**Comment by torresmi** [comment]
I like that! Would that require a major version bump?

**Comment by damienklinnert** [comment]
If we make a new method that would only be a minor one.

**Comment by damienklinnert** [comment]
Closing this since the PR got merged :)
