### ISSUE TITLE
Minimum supported Bridge version?

### ISSUE THREAD

**Issue by torresmi** [damienklinnert/elm-hue#6]
Related to #5, I realized that the test case was actually for version `1.3`. Versions less than that only return the light id and name for the `\lights` endpoint. This is the only example response I could find http://www.burgestrand.se/hue-api/api/lights/

```
{
  "1": {
    "name": "TV Left"
  },
  "2": {
    "name": "TV Right"
  }
}
```

I started to wonder if supporting `1.0` would do more harm than good. Basic things like Scenes, Sensors, and Rules all require higher bridge versions. The Hue API changelogs even start at version `1.4`, which seems like a good base version.

Any thoughts on requiring a minimum API version to support?

**Comment by damienklinnert** [comment]
Cool, I agree, then let's target 1.4, mention that explicitly in the docs and change everything newer to maybes :)
