### ISSUE TITLE
Multi-Success and Multi-Error responses

### ISSUE THREAD

**Issue by torresmi** [damienklinnert/elm-hue#8]
Some of the responses from `PUT` requests result in a list of success and Hue errors.

`PUT` `/lights/1/state` `{"on":false, "sat":253, "bri":254 }`

```
[
    {
        "error": {
            "type": 201,
            "address": "/lights/1/state/sat",
            "description": "parameter, sat, is not modifiable. Device is set to off."
        }
    },
    {
        "error": {
            "type": 201,
            "address": "/lights/1/state/bri",
            "description": "parameter, bri, is not modifiable. Device is set to off."
        }
    },
    {
        "success": {
            "/lights/1/state/on": false
        }
    }
]
```

Right now this would get routed to a `GenericError` type. Error handling here is tricky, but I have seen other libraries go the following route:
- Successful responses that contain `error` json are still considered a successful request. 
  - Separate IO errors from Hue errors
- `Put` requests return a list of errors.
  - Some return just errors, and some return a list of success operations as well.

**Comment by damienklinnert** [comment]
Good suggestion! In the case of returning a list of errors, how would you map those errors to the commands that failed?

**Comment by torresmi** [comment]
I was thinking that that these Hue errors wouldn't really be treated as failures, but instead more like additional response information.

```
type Msg 
  = UpdateLightSuccess List HueError
  | UpdateLightFailure Error
```

```
update msg =
    case msg of
        UpdateLightSuccess errors -> -- Successful response. Return CMD based on any Hue errors
        UpdateLightFailure error -> -- Unsuccessful response. IO Error routed from Task
```

Any operation not in the errors list could be considered a success. `Task` errors would just be IO related errors instead of IO and Hue errors. 

This is just for responses with multiple success and error responses, since it's hard to determine what actually is considered a failed or successful task when they are mixed. Other tasks that don't mix errors and successes could be treated differently, as either a total success or total failure.

**Comment by damienklinnert** [comment]
Gotcha! +1 for separating IO errors from update errors as proposed :)

Shall I also cut a release? You've made quite some improvements in the last couple of days.

**Comment by torresmi** [comment]
Cool, I'll make a branch to start trying out this pattern. 

A release sounds good to me :+1:

**Comment by damienklinnert** [comment]
Release 2.0.0 is out now :)

**Comment by torresmi** [comment]
Here is an API preview of some of my thoughts so far. 

[documentation.zip](https://github.com/damienklinnert/elm-hue/files/441452/documentation.zip)

http://package.elm-lang.org/help/docs-preview

## Overview

### Tasks
- Task error types are a `BridgeReferenceError` type, which tags any errors preventing us from properly issuing commands to the bridge.
  - IO and Authentication errors
    - Easier to handle re-auth cases that can happen on any command
- Task values are a `Result` type, with a `Err` containing Hue Bridge errors and an `Ok` containing the same values as before.
  - `Result` is clearer than saying an empty list of errors means a success. 

### Error types
- Certain Hue errors only exist for certain commands. I thought it would be cool to express that in the types, so you know whether or not you need to handle that case. 
  
  e.g. the `201` error above can only come back when updating a light, so no need to think about that when fetching all lights.
  - These cases get their own error types, which tag all the possible outcomes.
    - Example is `UpdateLightError`
- Generic Hue errors can be returned from many commands, like `InternalError`. I have these into a `GenericError` type that the consumer can pattern match on wanted ones or lump them together with `_`

I'm still experimenting with this, so any feedback would be great. If this seems like a good route then I can push up a separate branch with a little bit of work done and an updated example file.

**Comment by damienklinnert** [comment]
Thanks for the detailed writedown. Good thoughts! Big +1 for having Errors specific to each method (types :))
